# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_editor:
    name: Editor App

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Lerna
      run: npm install --global lerna
        
    - name: Bootstrap
      run: lerna bootstrap

    - name: Build Story Component
      run: cd packages/story-component && npm run build

    - name: Build Editor
      run: cd packages/editor-app && npm run build
      
    - name: Start Editor Server
      run: cd packages/editor-app && npm run start &
      
    - name: Test Editor
      run: cd packages/editor-app && npx cypress run
      
  test_story_app:
    name: Story App

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Lerna
      run: npm install --global lerna
        
    - name: Bootstrap
      run: lerna bootstrap

    - name: Build Story Component
      run: cd packages/story-component && npm run build

    - name: Build Stories
      run: cd packages/stories-app && npm run build
  
    - name: Start Stories Server
      run: cd packages/stories-app && npm run start &
      
    - name: Test Stories
      run: cd packages/stories-app && npx cypress run
      
